# -*- coding: utf-8 -*-
"""Advance_AI_2nd_Assignment_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HFSflBdMmdfm7U3NgP0Ln1XN8JvPJgGd
"""

!pip install -q transformers
!pip install -q datasets
!pip install -q sentencepiece
!pip install -q sacrebleu
!pip install -q evaluate
!pip install -q accelerate
!pip install -q bert-score
!pip install -q nltk

import pandas as pd
import numpy as np
import torch

from datasets import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    DataCollatorForSeq2Seq
)

train_sa = pd.read_csv("train_sa_10000.csv")
train_en = pd.read_csv("train_en_10000.csv")

dev_sa = pd.read_csv("dev_sa_1000.csv")
dev_en = pd.read_csv("dev_en_1000.csv")

test_sa = pd.read_csv("test_sa_1000.csv")
test_en = pd.read_csv("test_en_1000.csv")

train_df = train_sa.merge(train_en,on="Source_id")
dev_df = dev_sa.merge(dev_en,on="Source_id")
test_df = test_sa.merge(test_en,on="Source_id")

train_df = train_df.rename(
    columns={
        "Sentence_sa":"source",
        "Sentence_en":"target"
    }
)

dev_df = dev_df.rename(
    columns={
        "Sentence_sa":"source",
        "Sentence_en":"target"
    }
)

test_df = test_df.rename(
    columns={
        "Sentence_sa":"source",
        "Sentence_en":"target"
    }
)

train_dataset = Dataset.from_pandas(
    train_df[["source","target"]]
)

dev_dataset = Dataset.from_pandas(
    dev_df[["source","target"]]
)

test_dataset = Dataset.from_pandas(
    test_df[["source","target"]]
)

train_dataset

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

MODEL_NAME = "facebook/nllb-200-distilled-600M"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

device = "cuda" if torch.cuda.is_available() else "cpu"

model = model.to(device)

print("Loaded Successfully")

tokenizer

for lang_token in tokenizer.added_tokens_decoder.values():
    if "san" in lang_token.content.lower():
        print(lang_token.content)

SRC_LANG = "san_Deva"
TGT_LANG = "eng_Latn"

tokenizer.src_lang = SRC_LANG

sample = train_df.iloc[0]["source"]

tokens = tokenizer(sample)

print(sample)

print(tokens["input_ids"][:20])

decoded = tokenizer.decode(
    tokens["input_ids"],
    skip_special_tokens=True
)

print(decoded)

sample = train_df.iloc[0]["source"]

inputs = tokenizer(
    sample,
    return_tensors="pt"
).to(device)

# Find the token ID for the target language
target_lang_token_id = None
for token_id, added_token in tokenizer.added_tokens_decoder.items():
    if added_token.content == TGT_LANG:
        target_lang_token_id = token_id
        break

if target_lang_token_id is None:
    raise ValueError(f"Language token ID for '{TGT_LANG}' not found in tokenizer.added_tokens_decoder.")

generated_ids = model.generate(
    **inputs,
    forced_bos_token_id=target_lang_token_id,
    max_length=64
)

prediction = tokenizer.batch_decode(
    generated_ids,
    skip_special_tokens=True
)

print("Input:")
print(sample)

print("\nPrediction:")
print(prediction[0])

print("\nReference:")
print(train_df.iloc[0]["target"])

!pip install -q peft bitsandbytes

from peft import (
    LoraConfig,
    get_peft_model,
    TaskType
)

from transformers import DataCollatorForSeq2Seq

lora_config = LoraConfig(

    task_type=TaskType.SEQ_2_SEQ_LM,

    inference_mode=False,

    r=16,

    lora_alpha=32,

    lora_dropout=0.1,

    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj"
    ]
)

!pip install --upgrade torchao

model = get_peft_model(
    model,
    lora_config
)

model.print_trainable_parameters()

device = "cuda" if torch.cuda.is_available() else "cpu"

model.to(device)

MAX_SOURCE_LENGTH = 128
MAX_TARGET_LENGTH = 128


def preprocess(example):

    model_inputs = tokenizer(
        example["source"],
        max_length=MAX_SOURCE_LENGTH,
        truncation=True
    )

    labels = tokenizer(
        text_target=example["target"],
        max_length=MAX_TARGET_LENGTH,
        truncation=True
    )

    model_inputs["labels"] = labels["input_ids"]

    return model_inputs


train_dataset = train_dataset.map(
    preprocess,
    batched=True,
    remove_columns=train_dataset.column_names
)

dev_dataset = dev_dataset.map(
    preprocess,
    batched=True,
    remove_columns=dev_dataset.column_names
)

test_dataset = test_dataset.map(
    preprocess,
    batched=True,
    remove_columns=test_dataset.column_names
)

print(train_dataset[0])

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model
)

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model
)

!pip install -q evaluate

import evaluate
import numpy as np

from transformers import (
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    EarlyStoppingCallback
)

bleu = evaluate.load("sacrebleu")

def compute_metrics(eval_preds):

    predictions, labels = eval_preds

    if isinstance(predictions, tuple):
        predictions = predictions[0]

    decoded_preds = tokenizer.batch_decode(
        predictions,
        skip_special_tokens=True
    )

    labels = np.where(
        labels != -100,
        labels,
        tokenizer.pad_token_id
    )

    decoded_labels = tokenizer.batch_decode(
        labels,
        skip_special_tokens=True
    )

    decoded_labels = [[label] for label in decoded_labels]

    bleu_score = bleu.compute(
        predictions=decoded_preds,
        references=decoded_labels
    )

    return {
        "bleu": bleu_score["score"]
    }

training_args = Seq2SeqTrainingArguments(

    output_dir="./nllb_sanskrit",

    # overwrite_output_dir=True, # Removed due to TypeError

    num_train_epochs=10,

    learning_rate=2e-4,

    per_device_train_batch_size=8,

    per_device_eval_batch_size=8,

    gradient_accumulation_steps=2,

    predict_with_generate=True,

    generation_max_length=128,

    fp16=torch.cuda.is_available(),

    # evaluation_strategy="epoch",

    save_strategy="epoch",

    logging_strategy="steps",

    logging_steps=50,

    save_total_limit=2,

    load_best_model_at_end=False, # Changed to False to resolve ValueError

    metric_for_best_model="bleu",

    greater_is_better=True,

    report_to="none",

    warmup_ratio=0.1,

    weight_decay=0.01,

    lr_scheduler_type="cosine",

    remove_unused_columns=True
)

trainer = Seq2SeqTrainer(

    model=model,

    args=training_args,

    train_dataset=train_dataset,

    eval_dataset=dev_dataset,

    tokenizer=tokenizer,

    data_collator=data_collator,

    compute_metrics=compute_metrics,

    callbacks=[
        EarlyStoppingCallback(
            early_stopping_patience=3
        )
    ]
)

trainer.train()

trainer.save_model("best_nllb_model")

tokenizer.save_pretrained("best_nllb_model")

results = trainer.evaluate()

print(results)

def translate(sentence):

    tokenizer.src_lang = SRC_LANG

    inputs = tokenizer(
        sentence,
        return_tensors="pt"
    ).to(device)

    # Find the token ID for the target language (similar to previous successful approach)
    target_lang_token_id = None
    for token_id, added_token in tokenizer.added_tokens_decoder.items():
        if added_token.content == TGT_LANG:
            target_lang_token_id = token_id
            break

    if target_lang_token_id is None:
        raise ValueError(f"Language token ID for '{TGT_LANG}' not found in tokenizer.added_tokens_decoder.")

    generated_tokens = model.generate(
        **inputs,
        forced_bos_token_id=target_lang_token_id,
        max_length=128,
        num_beams=5,
        early_stopping=True
    )

    prediction = tokenizer.batch_decode(
        generated_tokens,
        skip_special_tokens=True
    )[0]

    return prediction

sample = dev_df.iloc[0]

print("SOURCE")
print(sample["source"])

print("\nREFERENCE")
print(sample["target"])

prediction = translate(
    sample["source"]
)

print("\nPREDICTION")
print(prediction)

from tqdm.auto import tqdm

predictions = []

for sentence in tqdm(test_df["source"]):

    pred = translate(sentence)

    predictions.append(pred)

test_df["prediction"] = predictions

submission = pd.DataFrame({

    "Source id": test_sa["Source_id"],

    "Sentence en": predictions

})

submission.to_csv(

    "submission.csv",

    index=False,

    encoding="utf-8"

)

print(submission.head())

trainer.save_model("best_nllb_model")

import shutil

shutil.make_archive(

    "best_nllb_model",

    "zip",

    "best_nllb_model"

)

from google.colab import files

files.download(
    "best_nllb_model.zip"
)

files.download(
    "submission.csv"
)

!pip install -q bert-score nltk

import time
import nltk
import pandas as pd

from nltk.translate.bleu_score import corpus_bleu
from bert_score import score

nltk.download("punkt")
nltk.download("punkt_tab")

from tqdm.auto import tqdm

predictions = []

start_time = time.time()

for sentence in tqdm(dev_df["source"]):

    tokenizer.src_lang = SRC_LANG

    inputs = tokenizer(
        sentence,
        return_tensors="pt"
    ).to(device)

    # Find the token ID for the target language (similar to previous successful approach)
    target_lang_token_id = None
    for token_id, added_token in tokenizer.added_tokens_decoder.items():
        if added_token.content == TGT_LANG:
            target_lang_token_id = token_id
            break

    if target_lang_token_id is None:
        raise ValueError(f"Language token ID for '{TGT_LANG}' not found in tokenizer.added_tokens_decoder.")

    generated_tokens = model.generate(
        **inputs,
        forced_bos_token_id=target_lang_token_id,
        num_beams=5,
        max_new_tokens=128,
        early_stopping=True
    )

    pred = tokenizer.batch_decode(
        generated_tokens,
        skip_special_tokens=True
    )[0]

    predictions.append(pred)

end_time = time.time()

total_inference_time = end_time - start_time

print(f"Total Inference Time : {total_inference_time:.2f} seconds")

references = [
    [nltk.word_tokenize(ref.lower())]
    for ref in dev_df["target"]
]

hypotheses = [
    nltk.word_tokenize(pred.lower())
    for pred in predictions
]

bleu_score = corpus_bleu(
    references,
    hypotheses
)

print("="*50)
print(f"NLTK BLEU : {bleu_score:.4f}")
print("="*50)

P, R, F1 = score(
    predictions,
    dev_df["target"].tolist(),
    lang="en",
    rescale_with_baseline=True
)

bert_f1 = F1.mean().item()

print("="*50)
print(f"BERTScore F1 : {bert_f1:.4f}")
print("="*50)

total_params = sum(
    p.numel()
    for p in model.parameters()
)

trainable_params = sum(
    p.numel()
    for p in model.parameters()
    if p.requires_grad
)

print("="*50)
print(f"Total Parameters      : {total_params:,}")
print(f"Trainable Parameters  : {trainable_params:,}")
print("="*50)

results = pd.DataFrame({

    "Metric":[
        "NLTK BLEU",
        "BERTScore F1",
        "Inference Time (seconds)",
        "Total Parameters",
        "Trainable Parameters"
    ],

    "Value":[
        bleu_score,
        bert_f1,
        total_inference_time,
        total_params,
        trainable_params
    ]
})

results

from tqdm.auto import tqdm
import pandas as pd

NUM_EXAMPLES = 10

examples = []

for i in range(NUM_EXAMPLES):

    source = dev_df.iloc[i]["source"]
    reference = dev_df.iloc[i]["target"]

    tokenizer.src_lang = SRC_LANG

    inputs = tokenizer(
        source,
        return_tensors="pt"
    ).to(device)

    # Find the token ID for the target language (reusing the successful approach)
    target_lang_token_id = None
    for token_id, added_token in tokenizer.added_tokens_decoder.items():
        if added_token.content == TGT_LANG:
            target_lang_token_id = token_id
            break

    if target_lang_token_id is None:
        raise ValueError(f"Language token ID for '{TGT_LANG}' not found in tokenizer.added_tokens_decoder.")

    generated_tokens = model.generate(
        **inputs,
        forced_bos_token_id=target_lang_token_id,
        num_beams=5,
        max_new_tokens=128,
        early_stopping=True
    )

    prediction = tokenizer.batch_decode(
        generated_tokens,
        skip_special_tokens=True
    )[0]

    examples.append({
        "Sanskrit": source,
        "Reference": reference,
        "Prediction": prediction
    })

examples_df = pd.DataFrame(examples)

examples_df.to_csv(
    "translation_examples.csv",
    index=False,
    encoding="utf-8"
)

for idx, row in examples_df.iterrows():

    print("=" * 120)
    print(f"Example {idx+1}")
    print()
    print("Sanskrit :")
    print(row["Sanskrit"])
    print()
    print("Reference :")
    print(row["Reference"])
    print()
    print("Prediction :")
    print(row["Prediction"])
    print()

print("\nSaved as translation_examples.csv")

import pandas as pd
import matplotlib.pyplot as plt

# Convert trainer logs to DataFrame
history = pd.DataFrame(trainer.state.log_history)

# Display available columns
print(history.columns)

import matplotlib.pyplot as plt

train_logs = history.dropna(subset=["loss"])

plt.figure(figsize=(8,5))

plt.plot(
    train_logs["step"],
    train_logs["loss"],
    marker="o",
    linewidth=2,
    label="Training Loss"
)

plt.xlabel("Training Steps")
plt.ylabel("Loss")
plt.title("Training Loss Curve")
plt.grid(True)
plt.legend()

plt.savefig(
    "training_loss_curve.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

eval_logs = history.dropna(subset=["eval_loss"])

plt.figure(figsize=(8,5))

plt.plot(
    eval_logs["epoch"],
    eval_logs["eval_loss"],
    marker="o",
    linewidth=2,
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Validation Loss")
plt.title("Validation Loss Curve")
plt.grid(True)
plt.legend()

plt.savefig(
    "validation_loss_curve.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

eval_logs = history.dropna(subset=["eval_bleu"])

plt.figure(figsize=(8,5))

plt.plot(
    eval_logs["epoch"],
    eval_logs["eval_bleu"],
    marker="o",
    linewidth=2,
    label="BLEU Score"
)

plt.xlabel("Epoch")
plt.ylabel("BLEU")
plt.title("Validation BLEU Score")
plt.grid(True)
plt.legend()

plt.savefig(
    "bleu_curve.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

fig, ax1 = plt.subplots(figsize=(9,5))

# Validation Loss
ax1.plot(
    eval_logs["epoch"],
    eval_logs["eval_loss"],
    color="tab:blue",
    marker="o",
    linewidth=2,
    label="Validation Loss"
)

ax1.set_xlabel("Epoch")
ax1.set_ylabel("Validation Loss", color="tab:blue")
ax1.tick_params(axis="y", labelcolor="tab:blue")

# BLEU on second axis
ax2 = ax1.twinx()

ax2.plot(
    eval_logs["epoch"],
    eval_logs["eval_bleu"],
    color="tab:red",
    marker="s",
    linewidth=2,
    label="BLEU"
)

ax2.set_ylabel("BLEU Score", color="tab:red")
ax2.tick_params(axis="y", labelcolor="tab:red")

plt.title("Validation Loss and BLEU Score During Fine-Tuning")

plt.savefig(
    "training_summary.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()